config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  resources :twits
  resources :followings, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twit.rb
class Twit < ApplicationRecord
  belongs_to :user
  validates :description, length: {minimum:20}
  validates_presence_of :user_id
  validates_presence_of :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :twits
  has_many :followers, class_name: "User", foreign_key: :follower_id
  has_many(:following, {class_name: "User", foreign_key: :following_id})
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    @following = current_user.followings.find(params[:following_id])
    @following.following_id = current_user.id
    if @following.save
      redirect_to twits_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  def index
    @twits = current_user.twits
    @followers = current_user.followers
    @following = current_user.following
  end

  def new
    @twit = current_user.twits.new
  end

  def create
    @twit = current_user.twits.new(twit_params)
    if @twit.save
      redirect_to twits_path
    else
      render :new
    end
  end

  private
  def twit_params
    params.require(:twit).permit(:description, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/views/followings/create.html.erb
<h1>Followings#create</h1>
<p>Find me in app/views/followings/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twiter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <br>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <ul class="col-md-4 col-md-offset-4 list-group text-center">
    <li class="list-group-item">
      <div class="video-list media">
        <div class="media-left">
          <img class="media-object" src={imageUrl} />
        </div>
      <div class="media-body">
        <div class="media-heading">
          <%-if current_user %>
            <h3><%= current_user.email%></h3>
          <%end %>
        </div>
      </div>
     </div>
    </li>
  </ul>

  <!-- <div class=row>
    <form>
      <div class="form-group">
       <div class="col-md-4 col-md-offset-4">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      </div>
      <div class="form-group">
        <div class="col-md-4 col-md-offset-4">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
      </div>
      <div class="form-check">
      <div class="col-md-4 col-md-offset-4">
        <label class="form-check-label">
          <input type="checkbox" class="form-check-input">
          Check me out
        </label>
      </div>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>
 -->

app/views/twits/index.html.erb
<h2> Followers </h2>
<%= @followers.count %>

<h2> Following </h2>

<%= @following.count %>

<h2> Mis Twits </h2>

<%= link_to("Crear Twit", new_twit_path, {class: "badge badge-primary btn-large"}) %>

<ul class="list-group">
  <%- @twits.each do |t| %>
    <li class="list-group-item"><%= t.description %></li>
    <br>
  <% end %>
</ul>

app/views/twits/new.html.erb
<!-- <div class=row>
  <form>
    <div class="form-group">
     <div class="col-md-4 col-md-offset-4">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    </div>
    <div class="form-group">
      <div class="col-md-4 col-md-offset-4">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>
    </div>
    <div class="form-check">
    <div class="col-md-4 col-md-offset-4">
      <label class="form-check-label">
        <input type="checkbox" class="form-check-input">
        Check me out
      </label>
    </div>
    </div>
    <div class="col-md-4 col-md-offset-4">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>
 -->

<% if @twit.errors.any? %>
  <ul>
    <% @twit.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div class="row">
  <%= form_for :twit, url: {action: "create"}, html: {class: "form-group"} do |f| %>
    <%= f.text_area :description %>
    <%= f.submit "Crear" %>
  <% end %>
</div>